#!/bin/bash

set -euo pipefail

PLUGIN_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)/.."

echo "--- :bullet: Download bullet logs"

artifacts_dir="$(pwd)/$(mktemp -d "bullet-report-artifacts-tmp.XXXXXXXXXX")"
annotation_dir="$(pwd)/$(mktemp -d "bullet-report-tmp.XXXXXXXXXX")"
annotation_path="${annotation_dir}/annotation.md"
annotation_style="info"

fail_build=0

function cleanup {
  rm -rf "${artifacts_dir}"
  rm -rf "${annotation_dir}"
}


trap cleanup EXIT

buildkite-agent artifact download \
  "log/bullet.log" \
  "${artifacts_dir}"
  # "${BUILDKITE_PLUGIN_BULLET_REPORT_PATTERN}" \

echo "--- :bullet: Processing bullet logs"

set +e
cat "${artifacts_dir}/*" | docker run -i --rm bandzoogle/bullet-report > bullet-report.txt

set -e

cat "${annotation_path}"

echo "--- :buildkite: Creating annotation"
# shellcheck disable=SC2002
cat "${annotation_path}" | buildkite-agent annotate --context "${BUILDKITE_PLUGIN_BULLET_REPORT_ANNOTATE_CONTEXT:-bullet}" --style "$annotation_style"

